import streamlit as st
import pandas as pd
import plotly.express as px
import json

st.set_page_config(layout="wide", page_title="Tactical Crime Forecasting Dashboard")

st.title("Tactical Crime Forecasting Dashboard")
st.markdown("Powered by Spatial CNN Hotspot Predictions and Historical Timelines")


# --- DATA PIPELINE ---
@st.cache_data
def load_dashboard_datasets():
    # 1. Load spatial snapshot predictions for the map layer
    pred_df = pd.read_csv("main/Dashboard/london_predictions.csv")
    pred_df['LSOA_code'] = pred_df['LSOA_code'].str.strip()

    # 2. Load the chronological timeline generated by your processing pipeline
    time_df = pd.read_csv("main/data/for training/cnn_code_based_crime_pipeline.csv")
    time_df['LSOA code'] = time_df['LSOA code'].str.strip()
    time_df['Month'] = pd.to_datetime(time_df['Month'])

    # 3. Load the official 2021 major cities skeleton map
    with open("main/Dashboard/major_cities_2021_skeleton.geojson", "r") as f:
        geojson_data = json.load(f)

    # 4. Flatten the GeoJSON features to map geographic codes to parent city hubs
    skeleton_records = []
    for feature in geojson_data["features"]:
        props = feature["properties"]
        skeleton_records.append({
            "LSOA21CD": props.get("LSOA21CD"),
            "LSOA21NM": props.get("LSOA21NM"),
            "LocalAuthority": props.get("LocalAuthority")
        })
    master_geo_df = pd.DataFrame(skeleton_records)

    london_boroughs = [
        "City of London", "Barking and Dagenham", "Barnet", "Bexley", "Brent", "Bromley",
        "Camden", "Croydon", "Ealing", "Enfield", "Greenwich", "Hackney", "Hammersmith and Fulham",
        "Haringey", "Harrow", "Havering", "Hillingdon", "Hounslow", "Islington",
        "Kensington and Chelsea", "Kingston upon Thames", "Lambeth", "Lewisham", "Merton",
        "Newham", "Redbridge", "Richmond upon Thames", "Southwark", "Sutton", "Tower Hamlets",
        "Waltham Forest", "Wandsworth", "Westminster"
    ]

    def normalize_to_hub(la_name):
        if la_name in london_boroughs:
            return "London"
        elif la_name in ["Kingston upon Hull", "Hull"]:
            return "Hull"
        return la_name

    master_geo_df['City_Hub'] = master_geo_df['LocalAuthority'].apply(normalize_to_hub)

    # 5. Build Map Dataframe (Left-join predictions onto the spatial skeleton)
    df_map_base = pd.merge(master_geo_df, pred_df, left_on="LSOA21CD", right_on="LSOA_code", how="left")
    df_map_base["matched_in_csv"] = df_map_base["LSOA_code"].notna()
    df_map_base["hotspot_probability"] = df_map_base["hotspot_probability"].fillna(0.0)
    df_map_base["crime_count"] = df_map_base["crime_count"].fillna(0)

    # 6. Build Historical Trend Dataframe (Inner-join timeline rows to regional city hub tags)
    df_trends_base = pd.merge(time_df, master_geo_df, left_on="LSOA code", right_on="LSOA21CD", how="inner")

    return df_map_base, df_trends_base, geojson_data


df_map, df_trends, geojson = load_dashboard_datasets()

# --- GPS VIEWPORTS ---
CITY_VIEWPORTS = {
    "All Cities": {"lat": 53.1, "lon": -1.6, "zoom": 6.0},
    "London": {"lat": 51.5074, "lon": -0.1278, "zoom": 9.5},
    "Birmingham": {"lat": 52.4862, "lon": -1.8904, "zoom": 11.0},
    "Manchester": {"lat": 53.4808, "lon": -2.2426, "zoom": 11.0},
    "Liverpool": {"lat": 53.4084, "lon": -2.9916, "zoom": 11.0},
    "Leeds": {"lat": 53.8008, "lon": -1.5491, "zoom": 10.5},
    "Sheffield": {"lat": 53.3811, "lon": -1.4701, "zoom": 11.0},
    "Newcastle upon Tyne": {"lat": 54.9783, "lon": -1.6178, "zoom": 11.0},
    "Leicester": {"lat": 52.6369, "lon": -1.1398, "zoom": 11.5},
    "Nottingham": {"lat": 52.9548, "lon": -1.1581, "zoom": 11.5},
    "Hull": {"lat": 53.7443, "lon": -0.3325, "zoom": 11.5}
}

# --- SIDEBAR CONTROLS ---
st.sidebar.header("Operational Scope")

raw_cities = sorted([c for c in df_map['City_Hub'].unique() if c])
available_cities = ["All Cities"] + raw_cities

selected_city = st.sidebar.selectbox("Select City ", available_cities, index=0)

# Filter operational data scopes conditionally
if selected_city == "All Cities":
    df_map_filtered = df_map
    df_trends_filtered = df_trends
    scope_text = "Nationwide Hubs"
else:
    df_map_filtered = df_map[df_map['City_Hub'] == selected_city]
    df_trends_filtered = df_trends[df_trends['City_Hub'] == selected_city]
    scope_text = selected_city

with st.sidebar.expander("Data Integrity Diagnostics"):
    st.write(f"Total Map Polygons: {len(df_map_filtered)}")
    st.write(f"Matched to Prediction Rows: {df_map_filtered['matched_in_csv'].sum()}")
    st.write(f"Historical Data Points: {len(df_trends_filtered)}")

# --- MAIN SCREEN: CHOROPLETH MAP ---
st.subheader(f"{scope_text} Strategic Crime Hotspot Map")

viewport = CITY_VIEWPORTS.get(selected_city, {"lat": 52.5, "lon": -1.5, "zoom": 6.0})

fig_map = px.choropleth_mapbox(
    df_map_filtered,
    geojson=geojson,
    locations="LSOA21CD",
    featureidkey="properties.LSOA21CD",
    color="hotspot_probability",
    color_continuous_scale="Reds",
    range_color=[0, 1],
    mapbox_style="carto-positron",
    zoom=viewport["zoom"],
    center={"lat": viewport["lat"], "lon": viewport["lon"]},
    opacity=0.6,
    labels={"hotspot_probability": "Hotspot Risk", "LSOA21NM": "Zone Name"},
    hover_data=["LSOA21NM", "crime_count", "City_Hub"]
)

fig_map.update_layout(margin={"r": 0, "t": 0, "l": 0, "b": 0}, height=600)
st.plotly_chart(fig_map, use_container_width=True)

st.markdown("---")
st.subheader("Tactical Trend Analytics")

chart_col1, chart_col2 = st.columns(2)

# --- CHART 1: LINE CHART FOR TOP RISK HOTSPOT LSOAs ---
with chart_col1:
    # Identify the top 5 highest-risk zones currently flagged by the model within selection
    top_hotspot_codes = (
        df_map_filtered.sort_values(by="hotspot_probability", ascending=False)
        .head(5)["LSOA21CD"]
        .values
    )

    # Isolate historical volume trends for these 5 high-risk zones
    df_hotspot_series = df_trends_filtered[df_trends_filtered['LSOA code'].isin(top_hotspot_codes)].copy()
    df_hotspot_series = df_hotspot_series.sort_values(by="Month")

    fig_line_hotspots = px.line(
        df_hotspot_series,
        x="Month",
        y="crime_count",
        color="LSOA21NM",
        title=f"Historical Crime Volume for Top 5 Hotspot Zones ({scope_text})",
        labels={"crime_count": "Monthly Crimes", "Month": "Timeline Month", "LSOA21NM": "Zone Name"},
        markers=True
    )
    fig_line_hotspots.update_layout(plot_bgcolor="rgba(0,0,0,0)", height=380)
    fig_line_hotspots.update_xaxes(showgrid=True, gridcolor="#f0f0f0")
    fig_line_hotspots.update_yaxes(showgrid=True, gridcolor="#f0f0f0")
    st.plotly_chart(fig_line_hotspots, use_container_width=True)

# --- CHART 2: LINE CHART FOR AGGREGATE REGIONAL TRAJECTORY ---
with chart_col2:
    # Group the selected scope chronologically to review total monthly volume shifts
    df_regional_aggregate = df_trends_filtered.groupby("Month")["crime_count"].sum().reset_index()
    df_regional_aggregate = df_regional_aggregate.sort_values(by="Month")

    fig_line_total = px.line(
        df_regional_aggregate,
        x="Month",
        y="crime_count",
        title=f"Aggregate Monthly Crime Trend ({scope_text})",
        labels={"crime_count": "Total Crime Count", "Month": "Timeline Month"},
        markers=True
    )
    fig_line_total.update_traces(line_color="#2b5c8f")
    fig_line_total.update_layout(plot_bgcolor="rgba(0,0,0,0)", height=380)
    fig_line_total.update_xaxes(showgrid=True, gridcolor="#f0f0f0")
    fig_line_total.update_yaxes(showgrid=True, gridcolor="#f0f0f0")
    st.plotly_chart(fig_line_total, use_container_width=True)